In [3]:
import pandas as pd

df_handles = pd.read_csv("s3://mt5599/collecting_handles/df_2016.csv")
df_handles

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (0,1,2,3,4,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,38,39,40,41,42,43,44,45,46,47) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unnamed: 0,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,...,user_statuses_count,user_favourites_count,user_listed_count,user_media_count,user_protected,user_link_url,link_tcourl,user_profile_image_url,user_profile_banner_url,user_label
0,0,https://twitter.com/EveRetana/status/660607096...,2015-10-31 23:59:40+00:00,Conociendo üëÄ‚òïÔ∏è (@ Entre-Nous in Heredia) https...,Conociendo üëÄ‚òïÔ∏è (@ Entre-Nous in Heredia) swarm...,6.606071e+17,"{'username': 'EveRetana', 'id': 310612528, 'di...",0.0,0,0,...,20690.0,6014.0,5.0,423.0,False,http://Instagram.com/everetana,https://t.co/aP3M7Ta5dh,https://pbs.twimg.com/profile_images/154670583...,https://pbs.twimg.com/profile_banners/31061252...,None
1,1,https://twitter.com/ferrg25/status/66060671608...,2015-10-31 23:58:09+00:00,üíë (@ Cin√©polis Paseo Metr√≥poli - @cinepoliscr ...,üíë (@ Cin√©polis Paseo Metr√≥poli - @cinepoliscr ...,6.606067e+17,"{'username': 'ferrg25', 'id': 759929504, 'disp...",0.0,0,0,...,52603.0,15658.0,3.0,812.0,False,None,None,https://pbs.twimg.com/profile_images/144180359...,https://pbs.twimg.com/profile_banners/75992950...,None
2,2,https://twitter.com/ZiortzaRuizJe/status/66060...,2015-10-31 23:57:56+00:00,"Buen d√≠a el de hoy de rali, en buena compa√±√≠a ...","Buen d√≠a el de hoy de rali, en buena compa√±√≠a ...",6.606067e+17,"{'username': 'ZiortzaRuizJe', 'id': 448840033,...",0.0,0,0,...,22349.0,1340.0,1.0,108.0,False,http://Instagram.com/ziortzaruizje,https://t.co/aHiPs172Gz,https://pbs.twimg.com/profile_images/148288529...,https://pbs.twimg.com/profile_banners/44884003...,None
3,3,https://twitter.com/gilf852/status/66060666089...,2015-10-31 23:57:56+00:00,@PPTeamLesslie yo soy fan de los polinecios,@PPTeamLesslie yo soy fan de los polinecios,6.606067e+17,"{'username': 'gilf852', 'id': 2384274093, 'dis...",0.0,0,0,...,11.0,10.0,0.0,0.0,False,None,None,https://pbs.twimg.com/profile_images/463701487...,https://pbs.twimg.com/profile_banners/23842740...,None
4,4,https://twitter.com/Nico_Fndz12/status/6606065...,2015-10-31 23:57:18+00:00,Mi jefe si vale la pena üëå (@ Quiznos in San Jo...,Mi jefe si vale la pena üëå (@ Quiznos in San Jo...,6.606065e+17,"{'username': 'Nico_Fndz12', 'id': 863160823, '...",0.0,0,0,...,5905.0,2340.0,1.0,151.0,False,None,None,https://pbs.twimg.com/profile_images/126601484...,https://pbs.twimg.com/profile_banners/86316082...,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057415,903457,https://twitter.com/RlByron/status/78200740335...,2016-10-01 00:01:08+00:00,Baile de Graduaci√≥n de mi hermana üî•üéâüéâüéâüéâüíÉ #GEN1...,Baile de Graduaci√≥n de mi hermana üî•üéâüéâüéâüéâüíÉ #GEN1...,7.820074e+17,"{'username': 'RlByron', 'id': 334739660, 'disp...",0.0,0,0,...,15917,48021,9,78,False,https://wa.link/ify2kk,https://t.co/hPcprMpc6V,https://pbs.twimg.com/profile_images/141435306...,https://pbs.twimg.com/profile_banners/33473966...,None
1057416,903458,https://twitter.com/melisag_th/status/78200732...,2016-10-01 00:00:49+00:00,Yo soy como ew coca. \nAlguien dice ron con co...,Yo soy como ew coca. \nAlguien dice ron con co...,7.820073e+17,"{'username': 'melisag_th', 'id': 308722594, 'd...",0.0,3,12,...,11229,46258,2,1120,False,https://instagram.com/meligthuel?r=nametag,https://t.co/cONDHWgMsP,https://pbs.twimg.com/profile_images/151624353...,https://pbs.twimg.com/profile_banners/30872259...,None
1057417,903459,https://twitter.com/Rudin_C/status/78200731815...,2016-10-01 00:00:48+00:00,I'm at Starbucks Plaza Freses - @starbucks_cr ...,I'm at Starbucks Plaza Freses - @starbucks_cr ...,7.820073e+17,"{'username': 'Rudin_C', 'id': 365636883, 'disp...",0.0,0,0,...,9518,8979,11,206,False,None,None,https://pbs.twimg.com/profile_images/990008851...,https://pbs.twimg.com/profile_banners/36563688...,None
1057418,903460,https://twitter.com/jp_monge/status/7820072954...,2016-10-01 00:00:42+00:00,üåÜ #sunset #nature #naturelovers #landscape #co...,üåÜ #sunset #nature #naturelovers #landscape #co...,7.820073e+17,"{'username': 'jp_monge', 'id': 807312132, 'dis...",0.0,0,0,...,4771,2149,74,963,False,https://www.instagram.com/j.p.monge.s/,https://t.co/0XfViX01fB,https://pbs.twimg.com/profile_images/156654048...,https://pbs.twimg.com/profile_banners/80731213...,None
1057419,903461,https://twitter.com/Melias26/status/7820071846...,2016-10-01 00:00:16+00:00,üí™ (@ Personal Fitness) https://t.co/ok73dbWEEV,üí™ (@ Personal Fitness) swarmapp.com/c/8Hxl7iWlEmU,7.820072e+17,"{'username': 'Melias26', 'id': 2444496445, 'di...",0.0,0,1,...,14772,17155,1,760,False,None,None,https://pbs.twimg.com/profile_images/151758246...,https://pbs.twimg.com/profile_banners/24444964...,None

In [6]:
df_handles.columns

Index(['Unnamed: 0', 'url', 'date', 'content', 'renderedContent', 'id', 'user',
       'replyCount', 'retweetCount', 'likeCount', 'quoteCount',
       'conversationId', 'lang', 'source', 'sourceUrl', 'sourceLabel',
       'outlinks', 'tcooutlinks', 'media', 'retweetedTweet', 'quotedTweet',
       'inReplyToTweetId', 'inReplyToUser', 'mentionedUsers', 'coordinates',
       'place', 'hashtags', 'cashtags', 'username', 'user_location', 'user_id',
       'displayname', 'user_description', 'user_description_urls',
       'user_verified', 'user_created', 'user_followers_count',
       'user_friends_count', 'user_statuses_count', 'user_favourites_count',
       'user_listed_count', 'user_media_count', 'user_protected',
       'user_link_url', 'link_tcourl', 'user_profile_image_url',
       'user_profile_banner_url', 'user_label'],
      dtype='object')

In [5]:
df_2016 = pd.read_feather("s3://mt5599/raw_tweets/2016/df_2016_tweets_cleaned_with_place.feather")
df_2016

,id,DateTime,tweet_content,cashtags,coordinates,hashtags,lang,like_count,media,mentioned_users,...,user_profile_image_url,user_profile_banner_url,user_label,resident/visitor,tweet,place_full_name,place_name,place_type,place_country,place_country_code
0,743561801745338368,2016-06-16 21:52:02,üòÅ https://t.co/eq2i7lxQkD,None,"Coordinates(longitude=-85.3044586, latitude=8....",None,und,1,[Photo(previewUrl='https://pbs.twimg.com/media...,None,...,https://pbs.twimg.com/profile_images/154994465...,https://pbs.twimg.com/profile_banners/59929935...,None,visitor,,"Puntarenas, Costa Rica",Puntarenas,admin,Costa Rica,CR
1,743064119754919936,2016-06-15 12:54:26,Morning ‚òïÔ∏èüå≤üçÇüåæüçÉ,None,"Coordinates(longitude=-85.3044586, latitude=8....",None,en,0,None,None,...,https://pbs.twimg.com/profile_images/154994465...,https://pbs.twimg.com/profile_banners/59929935...,None,visitor,morning,"Puntarenas, Costa Rica",Puntarenas,admin,Costa Rica,CR
2,742934385624809472,2016-06-15 04:18:55,üë¨üë≠‚ù§Ô∏èü§ó https://t.co/nMQNrePMXZ,None,None,None,und,0,[Photo(previewUrl='https://pbs.twimg.com/media...,None,...,https://pbs.twimg.com/profile_images/154994465...,https://pbs.twimg.com/profile_banners/59929935...,None,visitor,,None,None,None,None,None
3,726430125286264832,2016-04-30 15:16:52,Se van los 25 :/ https://t.co/RddGa6gT4T,None,None,None,es,3,[Photo(previewUrl='https://pbs.twimg.com/media...,None,...,https://pbs.twimg.com/profile_images/154994465...,https://pbs.twimg.com/profile_banners/59929935...,None,visitor,se van los 25 :/,None,None,None,None,None
4,684363985974464512,2016-01-05 13:21:03,Godo Morning üëì,None,"Coordinates(longitude=-84.851172, latitude=9.9...",None,en,1,None,None,...,https://pbs.twimg.com/profile_images/154994465...,https://pbs.twimg.com/profile_banners/59929935...,None,visitor,godo morning,"Puntarenas, Costa Rica",Puntarenas,city,Costa Rica,CR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7686538,649582930189156352,2015-10-01 13:53:33,El bus va vac√≠o pero no me voy a sentar com t...,None,"Coordinates(longitude=-84.2022247, latitude=9....",None,es,0,None,None,...,https://pbs.twimg.com/profile_images/157661616...,https://pbs.twimg.com/profile_banners/84109116...,None,resident,el bus va vaco pero no me voy a sentar com tal...,"Heredia, Costa Rica",Heredia,admin,Costa Rica,CR
7686539,649561708587954176,2015-10-01 12:29:14,Buenos d√≠as ! \nbienvenido octubre üëèüèº,None,"Coordinates(longitude=-85.4422302, latitude=9....",None,es,0,None,None,...,https://pbs.twimg.com/profile_images/157661616...,https://pbs.twimg.com/profile_banners/84109116...,None,resident,buenos das ! bienvenido octubre,"Alajuela, Costa Rica",Alajuela,admin,Costa Rica,CR
7686540,649446900601483264,2015-10-01 04:53:01,Y terminar comiendo una Queso de Mc üòä üòãüçî,None,None,None,es,0,None,None,...,https://pbs.twimg.com/profile_images/157661616...,https://pbs.twimg.com/profile_banners/84109116...,None,resident,y terminar comiendo una queso de mc,None,None,None,None,None
7686541,649435258853527552,2015-10-01 04:06:46,Gracias Mae por su culpa estoy que me vomito üò§,None,"Coordinates(longitude=-84.1299362, latitude=9....",None,es,0,None,None,...,https://pbs.twimg.com/profile_images/157661616...,https://pbs.twimg.com/profile_banners/84109116...,None,resident,gracias mae por su culpa estoy que me vomito,"Heredia, Costa Rica",Heredia,city,Costa Rica,CR
7686542,649434917596631040,2015-10-01 04:05:24,Un Mae se acaba de echar un una clase de perfu...,None,"Coordinates(longitude=-84.1299362, latitude=9....",None,es,0,None,None,...,https://pbs.twimg.com/profile_images/157661616...,https://pbs.twimg.com/profile_banners/84109116...,None,resident,un mae se acaba de echar un una clase de perfu...,"Heredia, Costa Rica",Heredia,city,Costa Rica,CR

In [ ]:
df_2016.place

In [7]:
df_2016["resident/visitor"].value_counts()

visitor     7539706
resident     146837
Name: resident/visitor, dtype: int64

In [9]:
pd.set_option('display.max_rows', None)
df_2016.place_country.value_counts(dropna=False)

None                                            5689456
Costa Rica                                      1599239
United States                                    109470
Nicaragua                                         47431
Argentina                                         27279
Spain                                             22944
Mexico                                            20541
United Kingdom                                    10514
Canada                                             9717
Panama                                             9545
Colombia                                           9155
Brazil                                             8879
Russia                                             8464
Chile                                              6613
Poland                                             5750
Venezuela                                          5712
Australia                                          4057
India                                              3993
Italy                                              3914
Germany                                            3783
Malaysia                                           3763
Thailand                                           3717
France                                             3569
Indonesia                                          3363
NaN                                                3354
El Salvador                                        3236
Dominican Republic                                 3126
Antarctica                                         2559
Peru                                               2523
Japan                                              2435
Honduras                                           2381
Guatemala                                          2225
Ecuador                                            2126
Vietnam                                            2040
Uruguay                                            1935
Republic of the Philippines                        1412
Belgium                                            1229
Taiwan                                             1204
Paraguay                                           1167
Kingdom of Saudi Arabia                            1146
Republic of Korea                                  1131
Greenland                                          1117
Egypt                                              1078
The Netherlands                                     895
Ireland                                             886
Belize                                              884
Norway                                              872
Austria                                             849
Algeria                                             838
Bolivia                                             827
New Zealand                                         744
Switzerland                                         738
Kazakhstan                                          728
Czech Republic                                      722
Sweden                                              720
Greece                                              693
Turkey                                              670
Israel                                              663
South Africa                                        621
Denmark                                             565
United Arab Emirates                                511
Portugal                                            479
Myanmar                                             476
Bulgaria                                            461
Republic of Croatia                                 445
Romania                                             440
Finland                                             389
Morocco                                             356
Singapore                                           355
Ukraine                                             352
Pakistan                                            327
Mongolia                                            316
Iraq                                                314
Democratic Republic of Congo                        307
Tanzania                                            300
Libya                                               275
Islamic Republic of Iran                            268
Hong Kong                                           251
Slovak Republic                                     251
Angola                                              246
Ghana                                               243
Sudan                                               243
Hungary                                             242
Chad                                                201
Aruba                                               201
Azerbaijan                                          187
Republic of Serbia                                  184
                                                    181
Mali                                                177
Qatar                                               177
Republic of Slovenia                                171
Niger                                               169
Ethiopia                                            169
Nigeria                                             167
Jamaica                                             163
Somalia                                             163
Mauritania                                          151
Cuba                                                147
Cura√ßao                                             146
Bangladesh                                          138
Kenya                                               134
Bahamas                                             127
Iceland                                             125
La R√©union                                          120
Lithuania                                           119
Republic of Mozambique                              118
Namibia                                             115
Georgia                                             112
Latvia                                              105
Tunisia                                             105
Estonia                                             105
Burkina Faso                                        103
Central African Republic                            100
Zambia                                               98
Uganda                                               98
Botswana                                             90
Uzbekistan                                           89
Papua New Guinea                                     83
French Polynesia                                     79
Turkmenistan                                         78
Madagascar                                           77
Cameroon                                             75
Afghanistan                                          73
Kuwait                                               73
Luxembourg                                           73
Yemen                                                70
Oman                                                 70
Trinidad and Tobago                                  64
Cambodia                                             63
Republic of Belarus                                  62
Zimbabwe                                             61
Kyrgyzstan                                           60
Maldives                                             59
Sri Lanka                                            58
Lebanon                                              53
Hashemite Kingdom of Jordan                          51
Congo Brazzaville                                    51
Ivory Coast                                          51
Guyana                                               51
Cayman Islands                                       50
Albania                                              50
Bosnia and Herzegovina                               48
Syria                                                46
Malta                                                44
Nepal                                                40
Guinea                                               40
Macau                                                38
Fiji                                                 37
Rwanda                                               34
Vatican City                                         34
Montenegro                                           33
Senegal                                              32
Saint Lucia                                          32
Haiti                                                31
Moldova                                              31
Cyprus                                               30
Barbados                                             30
Suriname                                             30
Bermuda                                              29
Saint Kitts and Nevis                                28
Kosovo                                               27
Gabon                                                26
Liberia                                              25
Tajikistan                                           25
Sint Maarten                                         25
Bonaire, Sint Eustatius and Saba                     21
Saint Barth√©lemy                                     20
North Korea                                          20
Guadeloupe                                           19
Guinea Bissau                                        19
Saint Martin                                         19
Former Yugoslav Republic of Macedonia                15
Lesotho                                              14
French Guiana                                        14
Turks and Caicos Islands                             13
Bhutan                                               13
Benin                                                13
Monaco                                               13
Malawi                                               11
Martinique                                           11
Eritrea                                              11
Seychelles                                           11
Sierra Leone                                          9
New Caledonia                                         9
Grenada                                               9
Solomon Islands                                       8
Togo                                                  8
Republic of Mauritius                                 8
Gibraltar                                             7
Swaziland                                             6
Armenia                                               6
Equatorial Guinea                                     5
Burundi                                               5
Falkland Islands (Malvinas)                           5
Antigua and Barbuda                                   5
Andorra                                               5
British Virgin Islands                                4
Norfolk Islands                                       4
Puerto Rico                                           3
Western Sahara                                        3
Samoa                                                 3
East Timor                                            3
Cape Verde                                            3
Djibouti                                              3
Dominica                                              3
S√£o Tom√© and Pr√≠ncipe                                 2
South Georgia and the South Sandwich Islands          2
Vanuatu                                               2
Bahrain                                               2
Faroe Islands                                         2
American Samoa                                        2
Cook Islands                                          2
Jersey                                                1
Anguilla                                              1
Liechtenstein                                         1
Brunei                                                1
French Southern and Antarctic Lands                   1
Comoros                                               1
Guam                                                  1
Mayotte                                               1
Gambia                                                1
Name: place_country, dtype: int64

In [11]:
27279 / (7686543 - 5689456)

0.0136593949086845

In [12]:
11/118

0.09322033898305085

In [3]:
import pandas as pd
import boto3

df_h = pd.read_json("s3://mt5599/tweets/handles_combined.json")
df_h
# how many geotagged tweets did we collect

,id,DateTime,tweet_content,cashtags,coordinates,hashtags,lang,like_count,media,mentioned_users,...,user_profile_image_url,user_profile_banner_url,user_label,place_country,place_country_code,place_full_name,place_name,place_type,coordinates_longitude,coordinates_latitude
0,671493915590057984,2015-12-01 00:59:59,mi fin de semana estuvo cabron,None,"Coordinates(longitude=-67.054105, latitude=18....",None,es,1,None,None,...,https://pbs.twimg.com/profile_images/160177785...,https://pbs.twimg.com/profile_banners/16040915...,None,United States,US,"Bejucos, Puerto Rico",Bejucos,city,-67.054105,18.481387
1,671493915497885696,2015-12-01 00:59:59,Ya me descarge el appüòÅ ahora mati no me va a p...,None,"Coordinates(longitude=-58.346384, latitude=-34...",None,es,1,None,None,...,https://pbs.twimg.com/profile_images/153241012...,https://pbs.twimg.com/profile_banners/22690117...,None,Argentina,AR,"Quilmes, Argentina",Quilmes,city,-58.346384,-34.801165
2,671493915342688256,2015-12-01 00:59:59,@gabyespinony Dejame buscar y te aviso !!!,None,"Coordinates(longitude=-73.3540725, latitude=0....",None,es,0,None,"[User(username='gabyespinony', id=2769738383, ...",...,https://pbs.twimg.com/profile_images/152098656...,None,None,Venezuela,VE,Venezuela,Venezuela,country,-73.354073,0.648837
3,671493914801643520,2015-12-01 00:59:59,Sin dudas la mejor gesti√≥n,None,"Coordinates(longitude=-64.3195, latitude=-31.5...",None,es,0,None,None,...,https://pbs.twimg.com/profile_images/160430215...,https://pbs.twimg.com/profile_banners/43886449...,None,Argentina,AR,"C√≥rdoba, Argentina",C√≥rdoba,city,-64.319500,-31.523576
4,671493914176724992,2015-12-01 00:59:59,Elbo Lita jajajaja que cldo!,None,"Coordinates(longitude=-64.389839, latitude=-33...",None,es,0,None,None,...,https://pbs.twimg.com/profile_images/140897405...,https://pbs.twimg.com/profile_banners/22708841...,None,Argentina,AR,"R√≠o Cuarto, Argentina",R√≠o Cuarto,city,-64.389839,-33.159419
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1655961,792863655096442880,2016-10-30 23:00:00,"@CFKArgentina con las propiedades de B√°ez,cua...",None,"Coordinates(longitude=-63.2919697, latitude=-3...",None,es,0,None,"[User(username='CFKArgentina', id=138814032, d...",...,https://pbs.twimg.com/profile_images/149981312...,https://pbs.twimg.com/profile_banners/76809874...,None,Argentina,AR,"General San Mart√≠n, Argentina",General San Mart√≠n,city,-63.291970,-32.432099
1655962,792863654274367488,2016-10-30 23:00:00,"Temperatura: 22,4¬∞C S.T√©rmica 22,4¬∞C PR 12,7¬∞C...",None,"Coordinates(longitude=-58.54916667, latitude=-...",None,es,1,None,None,...,https://pbs.twimg.com/profile_images/160486963...,https://pbs.twimg.com/profile_banners/47917531...,None,Argentina,AR,"Ciudad del Libertador General San Mart√≠n, Arge...",Ciudad del Libertador General San Mart√≠n,city,-58.549167,-34.535278
1655963,792863654089723904,2016-10-30 23:00:00,"que ondon Ram√≥n con el camar√≥n, que hongo joro...",None,"Coordinates(longitude=-97.43391558, latitude=3...",None,es,0,None,None,...,https://pbs.twimg.com/profile_images/839951285...,https://pbs.twimg.com/profile_banners/80163931...,None,United States,US,"Texas, USA",Texas,admin,-97.433916,30.346318
1655964,792863653401722880,2016-10-30 23:00:00,Extra√±aba esto ‚òÄ @ Nacimiento. Regi√≥n Bio Bio ...,None,"Coordinates(longitude=-72.6704209, latitude=-3...",None,es,0,None,None,...,https://pbs.twimg.com/profile_images/760588784...,https://pbs.twimg.com/profile_banners/21230792...,None,Chile,CL,"Nacimiento, Chile",Nacimiento,city,-72.670421,-37.501660
1655965,792863653129285632,2016-10-30 23:00:00,B√°rbara y Adara a la calle ya #DBT8GH17,None,"Coordinates(longitude=-8.0037342, latitude=42....",['DBT8GH17'],es,4,None,None,...,https://pbs.twimg.com/profile_images/136485738...,https://pbs.twimg.com/profile_banners/10150000...,None,Spain,ES,"Ourense, Spain",Ourense,city,-8.003734,42.288179

In [4]:
# how many usernames did we extract
len(df_h.username.unique())

417240

In [7]:
# how many tweets were from Argentina
df_h_ar = df_h[df_h.place_country == "Argentina"]
df_h_ar

,id,DateTime,tweet_content,cashtags,coordinates,hashtags,lang,like_count,media,mentioned_users,...,user_profile_image_url,user_profile_banner_url,user_label,place_country,place_country_code,place_full_name,place_name,place_type,coordinates_longitude,coordinates_latitude
1,671493915497885696,2015-12-01 00:59:59,Ya me descarge el appüòÅ ahora mati no me va a p...,None,"Coordinates(longitude=-58.346384, latitude=-34...",None,es,1,None,None,...,https://pbs.twimg.com/profile_images/153241012...,https://pbs.twimg.com/profile_banners/22690117...,None,Argentina,AR,"Quilmes, Argentina",Quilmes,city,-58.346384,-34.801165
3,671493914801643520,2015-12-01 00:59:59,Sin dudas la mejor gesti√≥n,None,"Coordinates(longitude=-64.3195, latitude=-31.5...",None,es,0,None,None,...,https://pbs.twimg.com/profile_images/160430215...,https://pbs.twimg.com/profile_banners/43886449...,None,Argentina,AR,"C√≥rdoba, Argentina",C√≥rdoba,city,-64.319500,-31.523576
4,671493914176724992,2015-12-01 00:59:59,Elbo Lita jajajaja que cldo!,None,"Coordinates(longitude=-64.389839, latitude=-33...",None,es,0,None,None,...,https://pbs.twimg.com/profile_images/140897405...,https://pbs.twimg.com/profile_banners/22708841...,None,Argentina,AR,"R√≠o Cuarto, Argentina",R√≠o Cuarto,city,-64.389839,-33.159419
6,671493913274949632,2015-12-01 00:59:59,Me re tatuar√≠a los gemelos,None,"Coordinates(longitude=-58.855831, latitude=-34...",None,es,0,None,None,...,https://pbs.twimg.com/profile_images/160436956...,https://pbs.twimg.com/profile_banners/74821488...,None,Argentina,AR,"Merlo, Argentina",Merlo,city,-58.855831,-34.770890
7,671493913065201664,2015-12-01 00:59:59,El sue√±o tengo diaaaassss,None,"Coordinates(longitude=-62.889222, latitude=-34...",None,es,0,None,None,...,https://pbs.twimg.com/profile_images/111362170...,https://pbs.twimg.com/profile_banners/28414455...,None,Argentina,AR,"Santa Fe, Argentina",Santa Fe,admin,-62.889222,-34.384296
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1655947,792863661719228416,2016-10-30 23:00:02,Me gustaria que cuando venga la vieja a visita...,None,"Coordinates(longitude=-58.160874, latitude=-35...",None,es,1,None,None,...,https://pbs.twimg.com/profile_images/748246613...,https://pbs.twimg.com/profile_banners/25129075...,None,Argentina,AR,"La Plata, Argentina",La Plata,city,-58.160874,-35.031373
1655956,792863659332599808,2016-10-30 23:00:01,@Luly_Busaniche activame a las piixq me duermoo,None,"Coordinates(longitude=-58.5317922, latitude=-3...",None,es,0,None,"[User(username='Luly_Busaniche', id=2255450796...",...,https://pbs.twimg.com/profile_images/120320916...,https://pbs.twimg.com/profile_banners/19095675...,None,Argentina,AR,"Ciudad Aut√≥noma de Buenos Aires, Argentina",Ciudad Aut√≥noma de Buenos Aires,city,-58.531792,-34.674453
1655959,792863656002351104,2016-10-30 23:00:00,"47' ST Se lo perdi√≥ #Sandoval solo, mano a man...",None,"Coordinates(longitude=-58.5317922, latitude=-3...","['Sandoval', 'Hoyos']",es,0,None,None,...,https://pbs.twimg.com/profile_images/115963399...,https://pbs.twimg.com/profile_banners/74594518...,None,Argentina,AR,"Ciudad Aut√≥noma de Buenos Aires, Argentina",Ciudad Aut√≥noma de Buenos Aires,city,-58.531792,-34.674453
1655961,792863655096442880,2016-10-30 23:00:00,"@CFKArgentina con las propiedades de B√°ez,cua...",None,"Coordinates(longitude=-63.2919697, latitude=-3...",None,es,0,None,"[User(username='CFKArgentina', id=138814032, d...",...,https://pbs.twimg.com/profile_images/149981312...,https://pbs.twimg.com/profile_banners/76809874...,None,Argentina,AR,"General San Mart√≠n, Argentina",General San Mart√≠n,city,-63.291970,-32.432099
1655962,792863654274367488,2016-10-30 23:00:00,"Temperatura: 22,4¬∞C S.T√©rmica 22,4¬∞C PR 12,7¬∞C...",None,"Coordinates(longitude=-58.54916667, latitude=-...",None,es,1,None,None,...,https://pbs.twimg.com/profile_images/160486963...,https://pbs.twimg.com/profile_banners/47917531...,None,Argentina,AR,"Ciudad del Libertador General San Mart√≠n, Arge...",Ciudad del Libertador General San Mart√≠n,city,-58.549167,-34.535278

In [8]:
# this corresponded to ___ users
len(df_h_ar.username.unique())

113632

In [2]:
import pandas as pd
import boto3

df_0 = pd.read_feather("s3://mt5599/tweets/spanish_tweets_2016_processed_wcontent_cleaned_0.feather")
df_0

,id,DateTime,coordinates,place,username,user_id,user_location,tweet_content,lang,tweet_clean,place_full_name,place_name,place_type,place_country,place_country_code,coordinates_longitude,coordinates_latitude
0,722512957247242240,2016-04-19 19:51:27+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,https://t.co/CGRUcZWccL,zxx,,None,None,None,None,None,NaN,NaN
1,718879627956068352,2016-04-09 19:13:54+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,Que chiste m√°s malo pero me rio igual,es,Que chiste m√°s malo pero me rio igual,None,None,None,None,None,NaN,NaN
2,718879522431639552,2016-04-09 19:13:28+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,"Habia perro llamado pegento, se callo y se pego",es,"Habia perro llamado pegento, se callo y se pego",None,None,None,None,None,NaN,NaN
3,718878528020852736,2016-04-09 19:09:31+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,Siento que cada d√≠a que pasa es un d√≠a menos p...,es,Siento que cada d√≠a que pasa es un d√≠a menos p...,None,None,None,None,None,NaN,NaN
4,718240922379644928,2016-04-08 00:55:54+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,La zorra dr mierda va un paso adelante y yo un...,es,La zorra dr mierda va un paso adelante y yo un...,None,None,None,None,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56370595,649383708659683328,2015-10-01 00:41:55+00:00,None,None,a_abrilcabrera,3295229884,,üíïüíï http://t.co/ME7bHBHswA,und,,None,None,None,None,None,NaN,NaN
56370596,649382730921283584,2015-10-01 00:38:02+00:00,None,None,a_abrilcabrera,3295229884,,tengo demasiadas fotos para hacerte poner celo...,es,tengo demasiadas fotos para hacerte poner celoso,None,None,None,None,None,NaN,NaN
56370597,649381096946298880,2015-10-01 00:31:33+00:00,None,None,a_abrilcabrera,3295229884,,No te cambio por nada negro feooo!!!! Aunque d...,es,No te cambio por nada negro feooo!!!! Aunque d...,None,None,None,None,None,NaN,NaN
56370598,649378695820537856,2015-10-01 00:22:00+00:00,None,None,a_abrilcabrera,3295229884,,"nadie me banda , una mas no me hace nada üòöüòö",es,"nadie me banda , una mas no me hace nada",None,None,None,None,None,NaN,NaN
56370599,649378607190646784,2015-10-01 00:21:39+00:00,None,None,a_abrilcabrera,3295229884,,"no me banques , me chupa huevo jajaüëàüòÇüëå",es,"no me banques , me chupa huevo jaja",None,None,None,None,None,NaN,NaN

In [3]:
pd.set_option('display.max_rows', None)
val_count0 = df_0.place_country.value_counts(dropna=False).rename_axis('unique_values').reset_index(name='counts')

In [4]:
pd.set_option('display.max_rows', 10)

df_1 = pd.read_feather("s3://mt5599/tweets/spanish_tweets_2016_processed_wcontent_cleaned_0.feather")
df_1

,id,DateTime,coordinates,place,username,user_id,user_location,tweet_content,lang,tweet_clean,place_full_name,place_name,place_type,place_country,place_country_code,coordinates_longitude,coordinates_latitude
0,722512957247242240,2016-04-19 19:51:27+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,https://t.co/CGRUcZWccL,zxx,,None,None,None,None,None,NaN,NaN
1,718879627956068352,2016-04-09 19:13:54+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,Que chiste m√°s malo pero me rio igual,es,Que chiste m√°s malo pero me rio igual,None,None,None,None,None,NaN,NaN
2,718879522431639552,2016-04-09 19:13:28+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,"Habia perro llamado pegento, se callo y se pego",es,"Habia perro llamado pegento, se callo y se pego",None,None,None,None,None,NaN,NaN
3,718878528020852736,2016-04-09 19:09:31+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,Siento que cada d√≠a que pasa es un d√≠a menos p...,es,Siento que cada d√≠a que pasa es un d√≠a menos p...,None,None,None,None,None,NaN,NaN
4,718240922379644928,2016-04-08 00:55:54+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,La zorra dr mierda va un paso adelante y yo un...,es,La zorra dr mierda va un paso adelante y yo un...,None,None,None,None,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56370595,649383708659683328,2015-10-01 00:41:55+00:00,None,None,a_abrilcabrera,3295229884,,üíïüíï http://t.co/ME7bHBHswA,und,,None,None,None,None,None,NaN,NaN
56370596,649382730921283584,2015-10-01 00:38:02+00:00,None,None,a_abrilcabrera,3295229884,,tengo demasiadas fotos para hacerte poner celo...,es,tengo demasiadas fotos para hacerte poner celoso,None,None,None,None,None,NaN,NaN
56370597,649381096946298880,2015-10-01 00:31:33+00:00,None,None,a_abrilcabrera,3295229884,,No te cambio por nada negro feooo!!!! Aunque d...,es,No te cambio por nada negro feooo!!!! Aunque d...,None,None,None,None,None,NaN,NaN
56370598,649378695820537856,2015-10-01 00:22:00+00:00,None,None,a_abrilcabrera,3295229884,,"nadie me banda , una mas no me hace nada üòöüòö",es,"nadie me banda , una mas no me hace nada",None,None,None,None,None,NaN,NaN
56370599,649378607190646784,2015-10-01 00:21:39+00:00,None,None,a_abrilcabrera,3295229884,,"no me banques , me chupa huevo jajaüëàüòÇüëå",es,"no me banques , me chupa huevo jaja",None,None,None,None,None,NaN,NaN

In [5]:
pd.set_option('display.max_rows', None)
val_count1 = df_1.place_country.value_counts(dropna=False).rename_axis('unique_values').reset_index(name='counts')

In [6]:
pd.set_option('display.max_rows', 10)
df_2 = pd.read_feather("s3://mt5599/tweets/spanish_tweets_2016_processed_wcontent_cleaned_0.feather")
df_2

,id,DateTime,coordinates,place,username,user_id,user_location,tweet_content,lang,tweet_clean,place_full_name,place_name,place_type,place_country,place_country_code,coordinates_longitude,coordinates_latitude
0,722512957247242240,2016-04-19 19:51:27+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,https://t.co/CGRUcZWccL,zxx,,None,None,None,None,None,NaN,NaN
1,718879627956068352,2016-04-09 19:13:54+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,Que chiste m√°s malo pero me rio igual,es,Que chiste m√°s malo pero me rio igual,None,None,None,None,None,NaN,NaN
2,718879522431639552,2016-04-09 19:13:28+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,"Habia perro llamado pegento, se callo y se pego",es,"Habia perro llamado pegento, se callo y se pego",None,None,None,None,None,NaN,NaN
3,718878528020852736,2016-04-09 19:09:31+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,Siento que cada d√≠a que pasa es un d√≠a menos p...,es,Siento que cada d√≠a que pasa es un d√≠a menos p...,None,None,None,None,None,NaN,NaN
4,718240922379644928,2016-04-08 00:55:54+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,La zorra dr mierda va un paso adelante y yo un...,es,La zorra dr mierda va un paso adelante y yo un...,None,None,None,None,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56370595,649383708659683328,2015-10-01 00:41:55+00:00,None,None,a_abrilcabrera,3295229884,,üíïüíï http://t.co/ME7bHBHswA,und,,None,None,None,None,None,NaN,NaN
56370596,649382730921283584,2015-10-01 00:38:02+00:00,None,None,a_abrilcabrera,3295229884,,tengo demasiadas fotos para hacerte poner celo...,es,tengo demasiadas fotos para hacerte poner celoso,None,None,None,None,None,NaN,NaN
56370597,649381096946298880,2015-10-01 00:31:33+00:00,None,None,a_abrilcabrera,3295229884,,No te cambio por nada negro feooo!!!! Aunque d...,es,No te cambio por nada negro feooo!!!! Aunque d...,None,None,None,None,None,NaN,NaN
56370598,649378695820537856,2015-10-01 00:22:00+00:00,None,None,a_abrilcabrera,3295229884,,"nadie me banda , una mas no me hace nada üòöüòö",es,"nadie me banda , una mas no me hace nada",None,None,None,None,None,NaN,NaN
56370599,649378607190646784,2015-10-01 00:21:39+00:00,None,None,a_abrilcabrera,3295229884,,"no me banques , me chupa huevo jajaüëàüòÇüëå",es,"no me banques , me chupa huevo jaja",None,None,None,None,None,NaN,NaN

In [7]:
pd.set_option('display.max_rows', None)
val_count2 = df_2.place_country.value_counts(dropna=False).rename_axis('unique_values').reset_index(name='counts')

In [8]:
pd.set_option('display.max_rows', 10)
df_3 = pd.read_feather("s3://mt5599/tweets/spanish_tweets_2016_processed_wcontent_cleaned_0.feather")
df_3

,id,DateTime,coordinates,place,username,user_id,user_location,tweet_content,lang,tweet_clean,place_full_name,place_name,place_type,place_country,place_country_code,coordinates_longitude,coordinates_latitude
0,722512957247242240,2016-04-19 19:51:27+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,https://t.co/CGRUcZWccL,zxx,,None,None,None,None,None,NaN,NaN
1,718879627956068352,2016-04-09 19:13:54+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,Que chiste m√°s malo pero me rio igual,es,Que chiste m√°s malo pero me rio igual,None,None,None,None,None,NaN,NaN
2,718879522431639552,2016-04-09 19:13:28+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,"Habia perro llamado pegento, se callo y se pego",es,"Habia perro llamado pegento, se callo y se pego",None,None,None,None,None,NaN,NaN
3,718878528020852736,2016-04-09 19:09:31+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,Siento que cada d√≠a que pasa es un d√≠a menos p...,es,Siento que cada d√≠a que pasa es un d√≠a menos p...,None,None,None,None,None,NaN,NaN
4,718240922379644928,2016-04-08 00:55:54+00:00,None,None,darcena2553,2358639522,No soy unica soy diferente,La zorra dr mierda va un paso adelante y yo un...,es,La zorra dr mierda va un paso adelante y yo un...,None,None,None,None,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56370595,649383708659683328,2015-10-01 00:41:55+00:00,None,None,a_abrilcabrera,3295229884,,üíïüíï http://t.co/ME7bHBHswA,und,,None,None,None,None,None,NaN,NaN
56370596,649382730921283584,2015-10-01 00:38:02+00:00,None,None,a_abrilcabrera,3295229884,,tengo demasiadas fotos para hacerte poner celo...,es,tengo demasiadas fotos para hacerte poner celoso,None,None,None,None,None,NaN,NaN
56370597,649381096946298880,2015-10-01 00:31:33+00:00,None,None,a_abrilcabrera,3295229884,,No te cambio por nada negro feooo!!!! Aunque d...,es,No te cambio por nada negro feooo!!!! Aunque d...,None,None,None,None,None,NaN,NaN
56370598,649378695820537856,2015-10-01 00:22:00+00:00,None,None,a_abrilcabrera,3295229884,,"nadie me banda , una mas no me hace nada üòöüòö",es,"nadie me banda , una mas no me hace nada",None,None,None,None,None,NaN,NaN
56370599,649378607190646784,2015-10-01 00:21:39+00:00,None,None,a_abrilcabrera,3295229884,,"no me banques , me chupa huevo jajaüëàüòÇüëå",es,"no me banques , me chupa huevo jaja",None,None,None,None,None,NaN,NaN

In [9]:
pd.set_option('display.max_rows', None)
val_count3 = df_3.place_country.value_counts(dropna=False).rename_axis('unique_values').reset_index(name='counts')

In [ ]:
val_count0 = df_0.place_country.value_counts(dropna=False).rename_axis('unique_values').reset_index(name='counts')
val_count1 = df_1.place_country.value_counts(dropna=False).rename_axis('unique_values').reset_index(name='counts')
val_count2 = df_2.place_country.value_counts(dropna=False).rename_axis('unique_values').reset_index(name='counts')
val_count3 = df_3.place_country.value_counts(dropna=False).rename_axis('unique_values').reset_index(name='counts')

In [43]:
val_count = pd.concat([val_count0, val_count1, val_count2, val_count3])

In [20]:
val_count0

                             unique_values    counts
0                                      NaN  35360586
1                                Argentina  20871042
2                                   Brazil     32353
3                            United States     26591
4                                  Uruguay     16979
5                                    Chile      9810
6                                   Mexico      6127
7                                    Spain      6034
8                                 Paraguay      4741
9                                  Ecuador      3102
10                          United Kingdom      2521
11                                Colombia      2325
12                                  Canada      2198
13                                  France      2099
14                                   Italy      1948
15                                 Germany      1730
16                      Dominican Republic      1686
17                                 Austria      1683
18                                    Peru      1681
19                                 Jamaica      1605
20                         The Netherlands      1010
21                                  Kuwait       992
22                               Venezuela       903
23                                Thailand       812
24                             New Zealand       730
25                               Guatemala       692
26                                 Bolivia       653
27                          Czech Republic       562
28                                   Japan       503
29                                  Israel       414
30                                Portugal       392
31                                  Russia       375
32                                Honduras       368
33                                   Egypt       367
34                                 Belgium       307
35                                 Finland       278
36                                  Panama       254
37                                  Greece       249
38                              Costa Rica       242
39                                  Turkey       217
40                                    Cuba       216
41                                   India       202
42                               Australia       198
43                                  Sweden       180
44                            South Africa       162
45                             Switzerland       161
46                    United Arab Emirates       153
47                                 Ireland       144
48                                 Denmark       120
49                                 Romania       116
50                               Singapore       110
51                 Kingdom of Saudi Arabia       102
52                               Indonesia       101
53                                 Bahamas        96
54                                  Norway        79
55                                Cambodia        65
56                                Malaysia        64
57                Islamic Republic of Iran        52
58                      Republic of Serbia        52
59                       Republic of Korea        50
60             Hashemite Kingdom of Jordan        48
61                               Hong Kong        46
62                        French Polynesia        46
63                            Vatican City        44
64             Republic of the Philippines        43
65                                Bulgaria        41
66                                 Cura√ßao        40
67                     Republic of Croatia        38
68                                 Estonia        37
69                                   Aruba        37
70                                 Hungary        33
71                                  Poland        32
72                                   Samoa        24
73                                   Nepal        22
74                             El Salvador        21
75                           French Guiana        21
76                                  Taiwan        19
77                             Afghanistan        18
78                                 Vietnam        18
79                                 Iceland        17
80                                 Tunisia        17
81                              San Marino        16
82                                  Monaco        15
83                                  Brunei        14
84                                 Morocco        14
85                                 Nigeria        14
86            Democratic Republic of Congo        13
87                               Nicaragua        13
88                           Liechtenstein        13
89                                  Angola        11
90                              Azerbaijan        11
91                                   Syria        10
92                                   Ghana        10
93                                Pakistan        10
94                Turks and Caicos Islands         9
95   Former Yugoslav Republic of Macedonia         9
96                                 Ukraine         9
97                                Maldives         9
98                                    Iraq         8
99                  Bosnia and Herzegovina         8
100                                  Qatar         8
101                                Andorra         7
102                              Sri Lanka         7
103                        Slovak Republic         7
104                                                6
105                             Bangladesh         6
106                                  Macau         5
107                                Senegal         5
108                              Lithuania         5
109                               Mongolia         5
110                                Lebanon         4
111                  Saint Kitts and Nevis         3
112                   Republic of Slovenia         3
113                             Luxembourg         3
114                                 Uganda         3
115                                Algeria         3
116                             Kazakhstan         3
117                                  Sudan         3
118                                  Malta         3
119                             Madagascar         3
120                           Turkmenistan         2
121                                Namibia         2
122                             Antarctica         2
123                                Bermuda         2
124                  Republic of Mauritius         2
125                         Cayman Islands         2
126                    Republic of Belarus         2
127                                   Mali         2
128                               Tanzania         2
129                                Myanmar         2
130                                Moldova         1
131                           Sierra Leone         1
132                           Saint Martin         1
133                                  Haiti         1
134                                 Kosovo         1
135                           Sint Maarten         1
136                                 Cyprus         1
137            Falkland Islands (Malvinas)         1
138                             Seychelles         1
139                             Uzbekistan         1
140                    Antigua and Barbuda         1
141                            Puerto Rico         1
142                               Zimbabwe         1
143                                 Belize         1
144                                 Rwanda         1
145                                Georgia         1
146                               Suriname         1
147                             Guadeloupe         1
148                                Armenia         1
149                               Ethiopia         1
150         Federated States of Micronesia         1
151                                Somalia         1
152                                   Fiji         1
153                                 Malawi         1
154                                Albania         1
155                            North Korea         1

In [12]:
val_count

                             unique_values    counts
0                                      NaN  35360586
1                                Argentina  20871042
2                                   Brazil     32353
3                            United States     26591
4                                  Uruguay     16979
5                                    Chile      9810
6                                   Mexico      6127
7                                    Spain      6034
8                                 Paraguay      4741
9                                  Ecuador      3102
10                          United Kingdom      2521
11                                Colombia      2325
12                                  Canada      2198
13                                  France      2099
14                                   Italy      1948
15                                 Germany      1730
16                      Dominican Republic      1686
17                                 Austria      1683
18                                    Peru      1681
19                                 Jamaica      1605
20                         The Netherlands      1010
21                                  Kuwait       992
22                               Venezuela       903
23                                Thailand       812
24                             New Zealand       730
25                               Guatemala       692
26                                 Bolivia       653
27                          Czech Republic       562
28                                   Japan       503
29                                  Israel       414
30                                Portugal       392
31                                  Russia       375
32                                Honduras       368
33                                   Egypt       367
34                                 Belgium       307
35                                 Finland       278
36                                  Panama       254
37                                  Greece       249
38                              Costa Rica       242
39                                  Turkey       217
40                                    Cuba       216
41                                   India       202
42                               Australia       198
43                                  Sweden       180
44                            South Africa       162
45                             Switzerland       161
46                    United Arab Emirates       153
47                                 Ireland       144
48                                 Denmark       120
49                                 Romania       116
50                               Singapore       110
51                 Kingdom of Saudi Arabia       102
52                               Indonesia       101
53                                 Bahamas        96
54                                  Norway        79
55                                Cambodia        65
56                                Malaysia        64
57                Islamic Republic of Iran        52
58                      Republic of Serbia        52
59                       Republic of Korea        50
60             Hashemite Kingdom of Jordan        48
61                               Hong Kong        46
62                        French Polynesia        46
63                            Vatican City        44
64             Republic of the Philippines        43
65                                Bulgaria        41
66                                 Cura√ßao        40
67                     Republic of Croatia        38
68                                 Estonia        37
69                                   Aruba        37
70                                 Hungary        33
71                                  Poland        32
72                                   Samoa        24
73                                   Nepal        22
74                             El Salvador        21
75                           French Guiana        21
76                                  Taiwan        19
77                             Afghanistan        18
78                                 Vietnam        18
79                                 Iceland        17
80                                 Tunisia        17
81                              San Marino        16
82                                  Monaco        15
83                                  Brunei        14
84                                 Morocco        14
85                                 Nigeria        14
86            Democratic Republic of Congo        13
87                               Nicaragua        13
88                           Liechtenstein        13
89                                  Angola        11
90                              Azerbaijan        11
91                                   Syria        10
92                                   Ghana        10
93                                Pakistan        10
94                Turks and Caicos Islands         9
95   Former Yugoslav Republic of Macedonia         9
96                                 Ukraine         9
97                                Maldives         9
98                                    Iraq         8
99                  Bosnia and Herzegovina         8
100                                  Qatar         8
101                                Andorra         7
102                              Sri Lanka         7
103                        Slovak Republic         7
104                                                6
105                             Bangladesh         6
106                                  Macau         5
107                                Senegal         5
108                              Lithuania         5
109                               Mongolia         5
110                                Lebanon         4
111                  Saint Kitts and Nevis         3
112                   Republic of Slovenia         3
113                             Luxembourg         3
114                                 Uganda         3
115                                Algeria         3
116                             Kazakhstan         3
117                                  Sudan         3
118                                  Malta         3
119                             Madagascar         3
120                           Turkmenistan         2
121                                Namibia         2
122                             Antarctica         2
123                                Bermuda         2
124                  Republic of Mauritius         2
125                         Cayman Islands         2
126                    Republic of Belarus         2
127                                   Mali         2
128                               Tanzania         2
129                                Myanmar         2
130                                Moldova         1
131                           Sierra Leone         1
132                           Saint Martin         1
133                                  Haiti         1
134                                 Kosovo         1
135                           Sint Maarten         1
136                                 Cyprus         1
137            Falkland Islands (Malvinas)         1
138                             Seychelles         1
139                             Uzbekistan         1
140                    Antigua and Barbuda         1
141                            Puerto Rico         1
142                               Zimbabwe         1
143                                 Belize         1
144                                 Rwanda         1
145                                Georgia         1
146                               Suriname         1
147                             Guadeloupe         1
148                                Armenia         1
149                               Ethiopia         1
150         Federated States of Micronesia         1
151                                Somalia         1
152                                   Fiji         1
153                                 Malawi         1
154                                Albania         1
155                            North Korea         1
0                                      NaN  35360586
1                                Argentina  20871042
2                                   Brazil     32353
3                            United States     26591
4                                  Uruguay     16979
5                                    Chile      9810
6                                   Mexico      6127
7                                    Spain      6034
8                                 Paraguay      4741
9                                  Ecuador      3102
10                          United Kingdom      2521
11                                Colombia      2325
12                                  Canada      2198
13                                  France      2099
14                                   Italy      1948
15                                 Germany      1730
16                      Dominican Republic      1686
17                                 Austria      1683
18                                    Peru      1681
19                                 Jamaica      1605
20                         The Netherlands      1010
21                                  Kuwait       992
22                               Venezuela       903
23                                Thailand       812
24                             New Zealand       730
25                               Guatemala       692
26                                 Bolivia       653
27                          Czech Republic       562
28                                   Japan       503
29                                  Israel       414
30                                Portugal       392
31                                  Russia       375
32                                Honduras       368
33                                   Egypt       367
34                                 Belgium       307
35                                 Finland       278
36                                  Panama       254
37                                  Greece       249
38                              Costa Rica       242
39                                  Turkey       217
40                                    Cuba       216
41                                   India       202
42                               Australia       198
43                                  Sweden       180
44                            South Africa       162
45                             Switzerland       161
46                    United Arab Emirates       153
47                                 Ireland       144
48                                 Denmark       120
49                                 Romania       116
50                               Singapore       110
51                 Kingdom of Saudi Arabia       102
52                               Indonesia       101
53                                 Bahamas        96
54                                  Norway        79
55                                Cambodia        65
56                                Malaysia        64
57                Islamic Republic of Iran        52
58                      Republic of Serbia        52
59                       Republic of Korea        50
60             Hashemite Kingdom of Jordan        48
61                               Hong Kong        46
62                        French Polynesia        46
63                            Vatican City        44
64             Republic of the Philippines        43
65                                Bulgaria        41
66                                 Cura√ßao        40
67                     Republic of Croatia        38
68                                 Estonia        37
69                                   Aruba        37
70                                 Hungary        33
71                                  Poland        32
72                                   Samoa        24
73                                   Nepal        22
74                             El Salvador        21
75                           French Guiana        21
76                                  Taiwan        19
77                             Afghanistan        18
78                                 Vietnam        18
79                                 Iceland        17
80                                 Tunisia        17
81                              San Marino        16
82                                  Monaco        15
83                                  Brunei        14
84                                 Morocco        14
85                                 Nigeria        14
86            Democratic Republic of Congo        13
87                               Nicaragua        13
88                           Liechtenstein        13
89                                  Angola        11
90                              Azerbaijan        11
91                                   Syria        10
92                                   Ghana        10
93                                Pakistan        10
94                Turks and Caicos Islands         9
95   Former Yugoslav Republic of Macedonia         9
96                                 Ukraine         9
97                                Maldives         9
98                                    Iraq         8
99                  Bosnia and Herzegovina         8
100                                  Qatar         8
101                                Andorra         7
102                              Sri Lanka         7
103                        Slovak Republic         7
104                                                6
105                             Bangladesh         6
106                                  Macau         5
107                                Senegal         5
108                              Lithuania         5
109                               Mongolia         5
110                                Lebanon         4
111                  Saint Kitts and Nevis         3
112                   Republic of Slovenia         3
113                             Luxembourg         3
114                                 Uganda         3
115                                Algeria         3
116                             Kazakhstan         3
117                                  Sudan         3
118                                  Malta         3
119                             Madagascar         3
120                           Turkmenistan         2
121                                Namibia         2
122                             Antarctica         2
123                                Bermuda         2
124                  Republic of Mauritius         2
125                         Cayman Islands         2
126                    Republic of Belarus         2
127                                   Mali         2
128                               Tanzania         2
129                                Myanmar         2
130                                Moldova         1
131                           Sierra Leone         1
132                           Saint Martin         1
133                                  Haiti         1
134                                 Kosovo         1
135                           Sint Maarten         1
136                                 Cyprus         1
137            Falkland Islands (Malvinas)         1
138                             Seychelles         1
139                             Uzbekistan         1
140                    Antigua and Barbuda         1
141                            Puerto Rico         1
142                               Zimbabwe         1
143                                 Belize         1
144                                 Rwanda         1
145                                Georgia         1
146                               Suriname         1
147                             Guadeloupe         1
148                                Armenia         1
149                               Ethiopia         1
150         Federated States of Micronesia         1
151                                Somalia         1
152                                   Fiji         1
153                                 Malawi         1
154                                Albania         1
155                            North Korea         1
0                                      NaN  35360586
1                                Argentina  20871042
2                                   Brazil     32353
3                            United States     26591
4                                  Uruguay     16979
5                                    Chile      9810
6                                   Mexico      6127
7                                    Spain      6034
8                                 Paraguay      4741
9                                  Ecuador      3102
10                          United Kingdom      2521
11                                Colombia      2325
12                                  Canada      2198
13                                  France      2099
14                                   Italy      1948
15                                 Germany      1730
16                      Dominican Republic      1686
17                                 Austria      1683
18                                    Peru      1681
19                                 Jamaica      1605
20                         The Netherlands      1010
21                                  Kuwait       992
22                               Venezuela       903
23                                Thailand       812
24                             New Zealand       730
25                               Guatemala       692
26                                 Bolivia       653
27                          Czech Republic       562
28                                   Japan       503
29                                  Israel       414
30                                Portugal       392
31                                  Russia       375
32                                Honduras       368
33                                   Egypt       367
34                                 Belgium       307
35                                 Finland       278
36                                  Panama       254
37                                  Greece       249
38                              Costa Rica       242
39                                  Turkey       217
40                                    Cuba       216
41                                   India       202
42                               Australia       198
43                                  Sweden       180
44                            South Africa       162
45                             Switzerland       161
46                    United Arab Emirates       153
47                                 Ireland       144
48                                 Denmark       120
49                                 Romania       116
50                               Singapore       110
51                 Kingdom of Saudi Arabia       102
52                               Indonesia       101
53                                 Bahamas        96
54                                  Norway        79
55                                Cambodia        65
56                                Malaysia        64
57                Islamic Republic of Iran        52
58                      Republic of Serbia        52
59                       Republic of Korea        50
60             Hashemite Kingdom of Jordan        48
61                               Hong Kong        46
62                        French Polynesia        46
63                            Vatican City        44

In [37]:
#val_count.loc[0,"unique_values"] = "NaN"
val_count.loc[0,"unique_values"]

0    NaN
0    NaN
0    NaN
0    NaN
Name: unique_values, dtype: object

In [44]:
val_count = val_count.groupby("unique_values", dropna=False).sum()
val_count

                                          counts
unique_values
                                              24
Afghanistan                                   72
Albania                                        4
Algeria                                       12
Andorra                                       28
Angola                                        44
Antarctica                                     8
Antigua and Barbuda                            4
Argentina                               83484168
Armenia                                        4
Aruba                                        148
Australia                                    792
Austria                                     6732
Azerbaijan                                    44
Bahamas                                      384
Bangladesh                                    24
Belgium                                     1228
Belize                                         4
Bermuda                                        8
Bolivia                                     2612
Bosnia and Herzegovina                        32
Brazil                                    129412
Brunei                                        56
Bulgaria                                     164
Cambodia                                     260
Canada                                      8792
Cayman Islands                                 8
Chile                                      39240
Colombia                                    9300
Costa Rica                                   968
Cuba                                         864
Cura√ßao                                      160
Cyprus                                         4
Czech Republic                              2248
Democratic Republic of Congo                  52
Denmark                                      480
Dominican Republic                          6744
Ecuador                                    12408
Egypt                                       1468
El Salvador                                   84
Estonia                                      148
Ethiopia                                       4
Falkland Islands (Malvinas)                    4
Federated States of Micronesia                 4
Fiji                                           4
Finland                                     1112
Former Yugoslav Republic of Macedonia         36
France                                      8396
French Guiana                                 84
French Polynesia                             184
Georgia                                        4
Germany                                     6920
Ghana                                         40
Greece                                       996
Guadeloupe                                     4
Guatemala                                   2768
Haiti                                          4
Hashemite Kingdom of Jordan                  192
Honduras                                    1472
Hong Kong                                    184
Hungary                                      132
Iceland                                       68
India                                        808
Indonesia                                    404
Iraq                                          32
Ireland                                      576
Islamic Republic of Iran                     208
Israel                                      1656
Italy                                       7792
Jamaica                                     6420
Japan                                       2012
Kazakhstan                                    12
Kingdom of Saudi Arabia                      408
Kosovo                                         4
Kuwait                                      3968
Lebanon                                       16
Liechtenstein                                 52
Lithuania                                     20
Luxembourg                                    12
Macau                                         20
Madagascar                                    12
Malawi                                         4
Malaysia                                     256
Maldives                                      36
Mali                                           8
Malta                                         12
Mexico                                     24508
Moldova                                        4
Monaco                                        60
Mongolia                                      20
Morocco                                       56
Myanmar                                        8
Namibia                                        8
Nepal                                         88
New Zealand                                 2920
Nicaragua                                     52
Nigeria                                       56
North Korea                                    4
Norway                                       316
Pakistan                                      40
Panama                                      1016
Paraguay                                   18964
Peru                                        6724
Poland                                       128
Portugal                                    1568
Puerto Rico                                    4
Qatar                                         32
Republic of Belarus                            8
Republic of Croatia                          152
Republic of Korea                            200
Republic of Mauritius                          8
Republic of Serbia                           208
Republic of Slovenia                          12
Republic of the Philippines                  172
Romania                                      464
Russia                                      1500
Rwanda                                         4
Saint Kitts and Nevis                         12
Saint Martin                                   4
Samoa                                         96
San Marino                                    64
Senegal                                       20
Seychelles                                     4
Sierra Leone                                   4
Singapore                                    440
Sint Maarten                                   4
Slovak Republic                               28
Somalia                                        4
South Africa                                 648
Spain                                      24136
Sri Lanka                                     28
Sudan                                         12
Suriname                                       4
Sweden                                       720
Switzerland                                  644
Syria                                         40
Taiwan                                        76
Tanzania                                       8
Thailand                                    3248
The Netherlands                             4040
Tunisia                                       68
Turkey                                       868
Turkmenistan                                   8
Turks and Caicos Islands                      36
Uganda                                        12
Ukraine                                       36
United Arab Emirates                         612
United Kingdom                             10084
United States                             106364
Uruguay                                    67916
Uzbekistan                                     4
Vatican City                                 176
Venezuela                                   3612
Vietnam                                       72
Zimbabwe                                       4
NaN                                    141442344

In [40]:
val_count.sum()

counts    2.254824e+08
%         2.683035e+02
dtype: float64

In [41]:
#141442344 +84,040,056

225482400

In [52]:
val_count["% geotagged"] = val_count.counts / 84040056 * 100
val_count["% total"] = val_count.counts/225482400*100
val_count = val_count.sort_values(by="counts", ascending=False)

In [54]:
val_count = val_count.round({"% geotagged":3, "% total":3})
val_count

                             unique_values     counts  % geotagged  % total
0                                      NaN  141442344      168.303   62.729
1                                Argentina   83484168       99.339   37.025
2                                   Brazil     129412        0.154    0.057
3                            United States     106364        0.127    0.047
4                                  Uruguay      67916        0.081    0.030
5                                    Chile      39240        0.047    0.017
6                                   Mexico      24508        0.029    0.011
7                                    Spain      24136        0.029    0.011
8                                 Paraguay      18964        0.023    0.008
9                                  Ecuador      12408        0.015    0.006
10                          United Kingdom      10084        0.012    0.004
11                                Colombia       9300        0.011    0.004
12                                  Canada       8792        0.010    0.004
13                                  France       8396        0.010    0.004
14                                   Italy       7792        0.009    0.003
15                                 Germany       6920        0.008    0.003
16                      Dominican Republic       6744        0.008    0.003
17                                 Austria       6732        0.008    0.003
18                                    Peru       6724        0.008    0.003
19                                 Jamaica       6420        0.008    0.003
20                         The Netherlands       4040        0.005    0.002
21                                  Kuwait       3968        0.005    0.002
22                               Venezuela       3612        0.004    0.002
23                                Thailand       3248        0.004    0.001
24                             New Zealand       2920        0.003    0.001
25                               Guatemala       2768        0.003    0.001
26                                 Bolivia       2612        0.003    0.001
27                          Czech Republic       2248        0.003    0.001
28                                   Japan       2012        0.002    0.001
29                                  Israel       1656        0.002    0.001
30                                Portugal       1568        0.002    0.001
31                                  Russia       1500        0.002    0.001
32                                Honduras       1472        0.002    0.001
33                                   Egypt       1468        0.002    0.001
34                                 Belgium       1228        0.001    0.001
35                                 Finland       1112        0.001    0.000
36                                  Panama       1016        0.001    0.000
37                                  Greece        996        0.001    0.000
38                              Costa Rica        968        0.001    0.000
39                                  Turkey        868        0.001    0.000
40                                    Cuba        864        0.001    0.000
41                                   India        808        0.001    0.000
42                               Australia        792        0.001    0.000
43                                  Sweden        720        0.001    0.000
44                            South Africa        648        0.001    0.000
45                             Switzerland        644        0.001    0.000
46                    United Arab Emirates        612        0.001    0.000
47                                 Ireland        576        0.001    0.000
48                                 Denmark        480        0.001    0.000
49                                 Romania        464        0.001    0.000
50                               Singapore        440        0.001    0.000
51                 Kingdom of Saudi Arabia        408        0.000    0.000
52                               Indonesia        404        0.000    0.000
53                                 Bahamas        384        0.000    0.000
54                                  Norway        316        0.000    0.000
55                                Cambodia        260        0.000    0.000
56                                Malaysia        256        0.000    0.000
58                Islamic Republic of Iran        208        0.000    0.000
57                      Republic of Serbia        208        0.000    0.000
59                       Republic of Korea        200        0.000    0.000
60             Hashemite Kingdom of Jordan        192        0.000    0.000
61                        French Polynesia        184        0.000    0.000
62                               Hong Kong        184        0.000    0.000
63                            Vatican City        176        0.000    0.000
64             Republic of the Philippines        172        0.000    0.000
65                                Bulgaria        164        0.000    0.000
66                                 Cura√ßao        160        0.000    0.000
67                     Republic of Croatia        152        0.000    0.000
68                                   Aruba        148        0.000    0.000
69                                 Estonia        148        0.000    0.000
70                                 Hungary        132        0.000    0.000
71                                  Poland        128        0.000    0.000
72                                   Samoa         96        0.000    0.000
73                                   Nepal         88        0.000    0.000
74                           French Guiana         84        0.000    0.000
75                             El Salvador         84        0.000    0.000
76                                  Taiwan         76        0.000    0.000
78                             Afghanistan         72        0.000    0.000
77                                 Vietnam         72        0.000    0.000
80                                 Iceland         68        0.000    0.000
79                                 Tunisia         68        0.000    0.000
81                              San Marino         64        0.000    0.000
82                                  Monaco         60        0.000    0.000
83                                 Morocco         56        0.000    0.000
84                                 Nigeria         56        0.000    0.000
85                                  Brunei         56        0.000    0.000
87                               Nicaragua         52        0.000    0.000
88                           Liechtenstein         52        0.000    0.000
86            Democratic Republic of Congo         52        0.000    0.000
89                              Azerbaijan         44        0.000    0.000
90                                  Angola         44        0.000    0.000
91                                Pakistan         40        0.000    0.000
92                                   Ghana         40        0.000    0.000
93                                   Syria         40        0.000    0.000
97   Former Yugoslav Republic of Macedonia         36        0.000    0.000
96                                Maldives         36        0.000    0.000
95                Turks and Caicos Islands         36        0.000    0.000
94                                 Ukraine         36        0.000    0.000
98                  Bosnia and Herzegovina         32        0.000    0.000
99                                    Iraq         32        0.000    0.000
100                                  Qatar         32        0.000    0.000
101                        Slovak Republic         28        0.000    0.000
102                                Andorra         28        0.000    0.000
103                              Sri Lanka         28        0.000    0.000
105                             Bangladesh         24        0.000    0.000
104                                                24        0.000    0.000
106                               Mongolia         20        0.000    0.000
107                              Lithuania         20        0.000    0.000
108                                  Macau         20        0.000    0.000
109                                Senegal         20        0.000    0.000
110                                Lebanon         16        0.000    0.000
118                   Republic of Slovenia         12        0.000    0.000
115                                  Sudan         12        0.000    0.000
119                                  Malta         12        0.000    0.000
116                             Madagascar         12        0.000    0.000
117                             Luxembourg         12        0.000    0.000
114                                 Uganda         12        0.000    0.000
112                  Saint Kitts and Nevis         12        0.000    0.000
111                             Kazakhstan         12        0.000    0.000
113                                Algeria         12        0.000    0.000
125                  Republic of Mauritius          8        0.000    0.000
128                    Republic of Belarus          8        0.000    0.000
127                             Antarctica          8        0.000    0.000
126                               Tanzania          8        0.000    0.000
129                                   Mali          8        0.000    0.000
124                                Bermuda          8        0.000    0.000
122                         Cayman Islands          8        0.000    0.000
121                           Turkmenistan          8        0.000    0.000
123                                Myanmar          8        0.000    0.000
120                                Namibia          8        0.000    0.000
149                                Somalia          4        0.000    0.000
145                                  Haiti          4        0.000    0.000
146                               Suriname          4        0.000    0.000
147                            North Korea          4        0.000    0.000
148                                 Kosovo          4        0.000    0.000
151                           Sint Maarten          4        0.000    0.000
150                                Moldova          4        0.000    0.000
152                           Sierra Leone          4        0.000    0.000
153                             Seychelles          4        0.000    0.000
154                                 Rwanda          4        0.000    0.000
143                                Georgia          4        0.000    0.000
144                             Guadeloupe          4        0.000    0.000
136                               Zimbabwe          4        0.000    0.000
142                                   Fiji          4        0.000    0.000
141                                 Malawi          4        0.000    0.000
140         Federated States of Micronesia          4        0.000    0.000
139                           Saint Martin          4        0.000    0.000
138                               Ethiopia          4        0.000    0.000
137                                 Cyprus          4        0.000    0.000
135                                Albania          4        0.000    0.000
134                                 Belize          4        0.000    0.000
133                             Uzbekistan          4        0.000    0.000
132                                Armenia          4        0.000    0.000
131            Falkland Islands (Malvinas)          4        0.000    0.000
130                    Antigua and Barbuda          4        0.000    0.000
155                            Puerto Rico          4        0.000    0.000

In [55]:
val_count = val_count.reset_index(drop=True)
val_count.to_csv("value_counts.csv", index=False)

In [3]:
import pandas as pd

df_handles = pd.read_feather("s3://mt5599/tweets/spanish_tweets_2016_10_processed_wcontent_ner.feather")
df_handles

,index,id,DateTime,coordinates,place,username,user_id,user_location,tweet_content,lang,tweet_clean,place_full_name,place_name,place_type,place_country,place_country_code,coordinates_longitude,coordinates_latitude,ner_type,ner_word
0,0,730197577686253568,2016-05-11 00:47:23+00:00,"Coordinates(longitude=-70.583131, latitude=-37...","Place(fullName='Mendoza, Argentina', name='Men...",studkintun,155906307,san Rafael,"@C5N Eduardo C√°ceres ""la Toyota por primera ve...",es,"Eduardo Cceres ""la Toyota por primera vez la ...","Mendoza, Argentina",Mendoza,admin,Argentina,AR,-70.583131,-37.577857,PER,Eduardo Cceres
1,1,730197577686253568,2016-05-11 00:47:23+00:00,"Coordinates(longitude=-70.583131, latitude=-37...","Place(fullName='Mendoza, Argentina', name='Men...",studkintun,155906307,san Rafael,"@C5N Eduardo C√°ceres ""la Toyota por primera ve...",es,"Eduardo Cceres ""la Toyota por primera vez la ...","Mendoza, Argentina",Mendoza,admin,Argentina,AR,-70.583131,-37.577857,ORG,Toyota
2,2,729471100552368128,2016-05-09 00:40:37+00:00,"Coordinates(longitude=-70.583131, latitude=-37...","Place(fullName='Mendoza, Argentina', name='Men...",studkintun,155906307,san Rafael,@EPoliticaC5N #MacriLoHizo,qme,MacriLoHizo,"Mendoza, Argentina",Mendoza,admin,Argentina,AR,-70.583131,-37.577857,None,None
3,3,729470812210794496,2016-05-09 00:39:29+00:00,"Coordinates(longitude=-70.583131, latitude=-37...","Place(fullName='Mendoza, Argentina', name='Men...",studkintun,155906307,san Rafael,@EPoliticaC5N iluminador,es,iluminador,"Mendoza, Argentina",Mendoza,admin,Argentina,AR,-70.583131,-37.577857,None,None
4,4,727877333592485888,2016-05-04 15:07:34+00:00,"Coordinates(longitude=-70.583131, latitude=-37...","Place(fullName='Mendoza, Argentina', name='Men...",studkintun,155906307,san Rafael,@Radio10 otra vez el impresentable,es,otra vez el impresentable,"Mendoza, Argentina",Mendoza,admin,Argentina,AR,-70.583131,-37.577857,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005756,1005756,649373226032738304,2015-10-01 00:00:16+00:00,"Coordinates(longitude=-58.3735, latitude=-34.6...",Place(fullName='Ciudad Aut√≥noma de Buenos Aire...,trendinaliaAR,1180083066,Argentina,1. #ARSAT2\n2. Bertolo\n3. MICAmpeona Se La BA...,es,1. ARSAT2 2. Bertolo 3. MICAmpeona Se La BANCA...,"Ciudad Aut√≥noma de Buenos Aires, Argentina",Ciudad Aut√≥noma de Buenos Aires,city,Argentina,AR,-58.373500,-34.608500,PER,MA
1005757,1005757,649373226032738304,2015-10-01 00:00:16+00:00,"Coordinates(longitude=-58.3735, latitude=-34.6...",Place(fullName='Ciudad Aut√≥noma de Buenos Aire...,trendinaliaAR,1180083066,Argentina,1. #ARSAT2\n2. Bertolo\n3. MICAmpeona Se La BA...,es,1. ARSAT2 2. Bertolo 3. MICAmpeona Se La BANCA...,"Ciudad Aut√≥noma de Buenos Aires, Argentina",Ciudad Aut√≥noma de Buenos Aires,city,Argentina,AR,-58.373500,-34.608500,ORG,##TI
1005758,1005758,649373226032738304,2015-10-01 00:00:16+00:00,"Coordinates(longitude=-58.3735, latitude=-34.6...",Place(fullName='Ciudad Aut√≥noma de Buenos Aire...,trendinaliaAR,1180083066,Argentina,1. #ARSAT2\n2. Bertolo\n3. MICAmpeona Se La BA...,es,1. ARSAT2 2. Bertolo 3. MICAmpeona Se La BANCA...,"Ciudad Aut√≥noma de Buenos Aires, Argentina",Ciudad Aut√≥noma de Buenos Aires,city,Argentina,AR,-58.373500,-34.608500,PER,##AS
1005759,1005759,649373226032738304,2015-10-01 00:00:16+00:00,"Coordinates(longitude=-58.3735, latitude=-34.6...",Place(fullName='Ciudad Aut√≥noma de Buenos Aire...,trendinaliaAR,1180083066,Argentina,1. #ARSAT2\n2. Bertolo\n3. MICAmpeona Se La BA...,es,1. ARSAT2 2. Bertolo 3. MICAmpeona Se La BANCA...,"Ciudad Aut√≥noma de Buenos Aires, Argentina",Ciudad Aut√≥noma de Buenos Aires,city,Argentina,AR,-58.373500,-34.608500,ORG,L
1005760,1005760,649373226032738304,2015-10-01 00:00:16+00:00,"Coordinates(longitude=-58.3735, latitude=-34.6...",Place(fullName='Ciudad Aut√≥noma de Buenos Aire...,trendinaliaAR,1180083066,Argentina,1. #ARSAT2\n2. Bertolo\n3. MICAmpeona Se La BA...,es,1. ARSAT2 2. Bertolo 3. MICAmpeona Se La BANCA...,"Ciudad Aut√≥noma de Buenos Aires, Argentina",Ciudad Aut√≥noma de Buenos Aires,city,Argentina,AR,-58.373500,-34.608500,PER,BR