In [2]:
import pyarrow.feather as feather
read_df = feather.read_feather('../data/dataset.feather')
read_df

,level_0,index,id,title,zoom_lat,zoom_lon,zoom_level,alert_id,feed_id,summary,...,admin1_code,admin2_code,admin3_code,admin4_code,cases_tags,deaths_tags,dates_end,precipitation_value,precipitation_mean,issue_month
0,0,0,8163513,['Dengue/DHF update (01): Americas'],39.783730,-100.445882,5,8163513,1,PRO/EDR> Dengue/DHF update (01): Americas,...,None,None,None,None,None,None,NaT,0.016949,0.070039,2
1,1,1,8163513,['Dengue/DHF update (01): Americas'],16.825979,-88.760093,5,8163513,1,PRO/EDR> Dengue/DHF update (01): Americas,...,None,None,None,None,None,None,NaT,0.116711,0.248139,2
2,2,2,8163513,['Dengue/DHF update (01): Americas'],10.273563,-84.073910,5,8163513,1,PRO/EDR> Dengue/DHF update (01): Americas,...,None,None,None,None,None,None,NaT,0.157389,0.424978,2
3,3,3,8163513,['Dengue/DHF update (01): Americas'],13.800038,-88.914068,5,8163513,1,PRO/EDR> Dengue/DHF update (01): Americas,...,None,None,None,None,None,None,NaT,0.019579,0.198830,2
4,4,4,8163513,['Dengue/DHF update (01): Americas'],15.635609,-89.898809,5,8163513,1,PRO/EDR> Dengue/DHF update (01): Americas,...,None,None,None,None,None,None,NaT,0.187086,0.292394,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098,2107,2107,17428,['Zika virus - Micronesia: Yap (04)'],6.492380,159.404221,5,17428,1,PRO/EDR> Zika virus - Micronesia: Yap (04),...,00,None,None,None,[case],None,2007-07-14,0.437677,0.409450,7
2099,2108,2108,15686,['Zika virus outbreak - Micronesia (Yap) (02):...,6.492380,159.404221,5,15686,1,PRO/AH/EDR> Zika virus outbreak - Micronesia (...,...,00,None,None,None,"[case, confirmed]",None,2007-07-03,0.437677,0.409450,7
2100,2109,2109,15805,"['Zika virus - Micronesia: Guam ex Yap, susp.']",6.492380,159.404221,5,15805,1,PRO/AH/EDR> Zika virus - Micronesia: Guam ex Y...,...,00,None,None,None,[case],None,2007-07-04,0.437677,0.409450,7
2101,2110,2110,16416,['Zika virus - Micronesia: Yap (03)'],6.492380,159.404221,5,16416,1,PRO/EDR> Zika virus - Micronesia: Yap (03),...,00,None,None,None,[case],None,2007-07-07,0.437677,0.409450,7
2102,2111,2111,14974,['Zika virus outbreak - Micronesia (Yap): susp...,6.492380,159.404221,5,14974,1,PRO/AH/EDR> Zika virus outbreak - Micronesia (...,...,00,None,None,None,[case],None,2007-06-28,0.481067,0.409450,6

In [3]:
read_df.columns

Index(['level_0', 'index', 'id', 'title', 'zoom_lat', 'zoom_lon', 'zoom_level',
       'alert_id', 'feed_id', 'summary', 'issue_date', 'load_date',
       'incident_date', 'descr', 'alert_tag_id', 'dup_count', 'dup_of',
       'unique_string', 'info_hash', 'submitted_by', 'reviewed',
       'search_string_id', 'content', 'disease', 'gpm_lat_idx', 'gpm_lon_idx',
       'precipitation_anomaly', 'location_name', 'dates_start', 'serotype',
       'total_cases', 'cases', 'severe_cases', 'deaths', 'admin1_code',
       'admin2_code', 'admin3_code', 'admin4_code', 'cases_tags',
       'deaths_tags', 'dates_end', 'precipitation_value', 'precipitation_mean',
       'issue_month'],
      dtype='object')

In [8]:
read_df[read_df["disease"]=="dengue"][["dates_start","location_name","cases"]]

    dates_start location_name  cases
0    2021-01-02           USA  307.0
1    2021-01-02        Belize  324.0
2    2021-01-02    Costa Rica  426.0
3    2020-12-26   El Salvador    0.0
4    2020-11-14     Guatemala  786.0
..          ...           ...    ...
783  2015-09-04       Ecuador    0.0
784  2015-09-11          Peru    0.0
785  2015-09-11     Argentina    0.0
786  2015-08-14        Brazil    0.0
787  2015-09-04      Paraguay    0.0

[788 rows x 3 columns]